package team.JavaTeens.ClientRequest;

public enum RequestType {

    SERVER_AUTHENTICATE,
    SERVER_COMMAND_PING,
    ADMIN_CREATE_USER_ACCOUNT,
    ADMIN_DELETE_USER_ACCOUNT,
    ADMIN_EDIT_USER_ACCOUNT,
    ADMIN_GET_ACCOUNTS_INFO,
    ADMIN_GET_LIST_OF_USERNAMES,
    USER_ADD_EVENT_DAY,
    USER_EDIT_SELF_ACCOUNT,
    USER_GET_ACCOUNT_INFO,
    USER_LOG_OFF,
    UNKNOWN
}
